export const GET_BREEDS = 'GET_BREEDS';
export const GET_BREED_DETAIL = 'GET_BREED_DETAIL';
export const CLEAR_PAGE = 'CLEAR_PAGE';
export const SEARCH_BREED = 'SEARCH_BREED';
export const SET_FAV = 'SET_FAV';
export const DEL_FAV = 'DEL_FAV';
export const CREATE_BREED = 'CREATE_BREED';
export const GET_TEMPERAMENT = 'GET_TEMPERAMENT';
export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';
export const FILTER_BY_CREATED = 'FILTER_BY_CREATED';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';

